baseURL = "http://davidfigueiredo.me"
languageCode = "en-us"
theme = "glim-midnight"
title = "David Figueriedo"

enableEmoji = true


[params]
    title = "David Figueiredo"
    phrases = ["Machine Learning", "Outsystems", "Python", "Django", "React JS"]
    links = [
    {name = "Github", url = "https://github.com/Zeimoto/", img_source = "/github.webp"},    
    {name = "LinkedIn", url = "https://www.linkedin.com/in/davidhfigueiredo/", img_source="/linkedin.webp"},
    {name = "Resume", url = "/curriculum.pdf"},    
    {name = "About me", url = "/about.md", img_source=""},    
    ] 
    background = "bg.mp4"

    [[params.socials]]
        name = "GitHub"
        url = "https://github.com/Zeimoto/"
        img_source = "/github.webp"    
    
    [[params.socials]]
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/davidhfigueiredo/"
        img_source="/linkedin.webp"
     

[menu]
    [[menu.main]]
        pageRef="about"
        name = "about"
        url = "/about/"
        weight = 20